export type DateFilter = "all" | "this-week" | "next-week";
export type PayFilter = "all" | "under-100" | "100-plus";

export type ShiftOffer = {
  id: string;
  shiftCode: string;
  organization: string;
  role: string;
  date: string;
  time: string;
  location: string;
  pay: string;
  postedAt: string;
  facilityName: string;
  address: string;
  notes: string;
  etaLabel: string;
  dateBucket: Exclude<DateFilter, "all">;
  payTier: Exclude<PayFilter, "all">;
};

export const shiftOffers: ShiftOffer[] = [
  {
    id: "offer-1",
    shiftCode: "SH33591",
    organization: "Biz Health tech",
    role: "Medical Doctor",
    date: "Sat, April 25",
    time: "8:00 AM - 10:00 AM",
    location: "Lekki, Lagos",
    pay: "$300",
    postedAt: "2:35 PM",
    facilityName: "Healthcare solutions",
    address: "12 Allen Avenue, Ikeja, Lagos",
    notes: "Report at the front desk and ask for the shift supervisor",
    etaLabel: "40 minutes",
    dateBucket: "this-week",
    payTier: "100-plus",
  },
  {
    id: "offer-2",
    shiftCode: "SH33592",
    organization: "EduTech Solutions",
    role: "Software Engineer",
    date: "Mon, May 1",
    time: "10:00 AM - 1:00 PM",
    location: "Victoria Island, Lagos",
    pay: "$120/hr",
    postedAt: "2:35 PM",
    facilityName: "EduTech main campus",
    address: "24 Adeola Odeku Street, Victoria Island, Lagos",
    notes: "Check in with the engineering operations desk before the session starts.",
    etaLabel: "40 minutes",
    dateBucket: "next-week",
    payTier: "100-plus",
  },
  {
    id: "offer-3",
    shiftCode: "SH33593",
    organization: "Green Energy Corp",
    role: "Project Manager",
    date: "Wed, May 10",
    time: "9:00 AM - 12:00 PM",
    location: "Ikeja, Lagos",
    pay: "$150/hr",
    postedAt: "2:35 PM",
    facilityName: "Healthcare solutions",
    address: "12 Allen Avenue, Ikeja, Lagos",
    notes: "Report at the front desk and ask for the shift supervisor",
    etaLabel: "40 minutes",
    dateBucket: "next-week",
    payTier: "100-plus",
  },
  {
    id: "offer-4",
    shiftCode: "SH33594",
    organization: "Biz Health tech",
    role: "Medical Doctor",
    date: "Sat, April 25",
    time: "8:00 AM - 10:00 AM",
    location: "Lekki, Lagos",
    pay: "$100/hr",
    postedAt: "2:35 PM",
    facilityName: "Biz Health satellite clinic",
    address: "18 Admiralty Way, Lekki Phase 1, Lagos",
    notes: "Bring your ID card and confirm your arrival with the assigned unit lead.",
    etaLabel: "40 minutes",
    dateBucket: "this-week",
    payTier: "100-plus",
  },
  {
    id: "offer-5",
    shiftCode: "SH33595",
    organization: "Edu Learn platform",
    role: "Instructor",
    date: "Mon, May 1",
    time: "10:00 AM - 12:00 PM",
    location: "Ikeja, Lagos",
    pay: "$75/hr",
    postedAt: "2:35 PM",
    facilityName: "Edu Learn training hub",
    address: "7 Obafemi Awolowo Way, Ikeja, Lagos",
    notes: "Presentation materials will be shared at the reception desk on arrival.",
    etaLabel: "40 minutes",
    dateBucket: "next-week",
    payTier: "under-100",
  },
  {
    id: "offer-6",
    shiftCode: "SH33596",
    organization: "FinTech Innovations",
    role: "Financial Analyst",
    date: "Wed, May 3",
    time: "1:00 PM - 3:00 PM",
    location: "Victoria Island, Lagos",
    pay: "$120/hr",
    postedAt: "2:35 PM",
    facilityName: "FinTech Innovations HQ",
    address: "31 Bishop Aboyade Cole Street, Victoria Island, Lagos",
    notes: "Proceed to the finance operations wing and sign the visitor register before entry.",
    etaLabel: "40 minutes",
    dateBucket: "next-week",
    payTier: "100-plus",
  },
  {
    id: "offer-7",
    shiftCode: "SH33597",
    organization: "Biz Health tech",
    role: "Medical Doctor",
    date: "Sat, April 25",
    time: "8:00 AM - 10:00 AM",
    location: "Lekki, Lagos",
    pay: "$100/hr",
    postedAt: "2:35 PM",
    facilityName: "Biz Health satellite clinic",
    address: "18 Admiralty Way, Lekki Phase 1, Lagos",
    notes: "Bring your ID card and confirm your arrival with the assigned unit lead.",
    etaLabel: "40 minutes",
    dateBucket: "this-week",
    payTier: "100-plus",
  },
  {
    id: "offer-8",
    shiftCode: "SH33598",
    organization: "Edu Learn platform",
    role: "Instructor",
    date: "Mon, May 1",
    time: "10:00 AM - 12:00 PM",
    location: "Ikeja, Lagos",
    pay: "$75/hr",
    postedAt: "2:35 PM",
    facilityName: "Edu Learn training hub",
    address: "7 Obafemi Awolowo Way, Ikeja, Lagos",
    notes: "Presentation materials will be shared at the reception desk on arrival.",
    etaLabel: "40 minutes",
    dateBucket: "next-week",
    payTier: "under-100",
  },
  {
    id: "offer-9",
    shiftCode: "SH33599",
    organization: "FinTech Innovations",
    role: "Financial Analyst",
    date: "Wed, May 3",
    time: "1:00 PM - 3:00 PM",
    location: "Victoria Island, Lagos",
    pay: "$120/hr",
    postedAt: "2:35 PM",
    facilityName: "FinTech Innovations HQ",
    address: "31 Bishop Aboyade Cole Street, Victoria Island, Lagos",
    notes: "Proceed to the finance operations wing and sign the visitor register before entry.",
    etaLabel: "40 minutes",
    dateBucket: "next-week",
    payTier: "100-plus",
  },
];
